### ISSUE TITLE
App not starting in heroku

### ISSUE THREAD

**Issue by omerh** [Snyk/pkgbot#4]
After build in heroku I get an error for
Error scaling dynos: Couldn't find that process type.

Also Docker image is not working

```
npm info it worked if it ends with ok
npm info using npm@4.0.5
npm info using node@v7.4.0
npm info lifecycle pkgbot@1.0.0~prestart: pkgbot@1.0.0
npm info lifecycle pkgbot@1.0.0~start: pkgbot@1.0.0

> pkgbot@1.0.0 start /home/node
> node .

module.js:472
    throw err;
    ^

Error: Cannot find module '/home/node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm info lifecycle pkgbot@1.0.0~start: Failed to exec start script
npm ERR! Linux 4.9.4-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! pkgbot@1.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pkgbot@1.0.0 start script 'node .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pkgbot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pkgbot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pkgbot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/node/npm-debug.log
```

 and npm start as well with the same exception

**Comment by karenyavine** [comment]
My bad 😁 
Give me a sec I'll fix that

**Comment by karenyavine** [comment]
https://github.com/Snyk/pkgbot/commit/b5ba3ad8e70ec418df5fc9e4d8896de66302dac9
Should work now! 😄
